fun main(){
    throw Exception("Hello Error!")
}